modLoader="javafml"
loaderVersion="[44,)"
credits="cpw"
authors="cpw"
license="GPLv3"
[[mods]]
    modId="inventorysorter"
    version="${file.jarVersion}"
    displayName="Simple Inventory Sorter"
    description='''
    Simple inventory sorting.

    Middle click to sort your inventory.
    Scroll wheel on a stack to move in and out.
    '''
[[dependencies.inventorysorter]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.inventorysorter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"