name: Bug Report
description: Report a bug / crash
labels: [ "bug", "unconfirmed" ]
body:
  - type: markdown
    attributes:
      value: |
        To help us help you, please provide as much information as you can, this helps us with debugging and reproducing the issue.
  - type: input
    id: mod-version
    attributes:
      label: Inventory Sorter Version
      description: |
        You can find the version of the mod in the mods file name or in-game in the mods button on the main menu.
      placeholder: 24.x.x
    validations:
      required: true
  - type: input
    id: neoforge-version
    attributes:
      label: NeoForge Version
      description: |
        You can get this from the main menu screen in the bottom left corner of the screen.
      placeholder: 21.1.x
    validations:
      required: false
  - type: input
    id: bugdesc
    attributes:
      label: Describe the issue
      description: |
        A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Tell us how we can reproduce the issue
      placeholder: |
        1. Open Mc...
        2. Use tool...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: "Link(s) to any log files that you can provide, typically, /logs/debug.log and /logs/latest.log. You can use services like [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) to upload your logs or you can drag them into the text box."
      placeholder: |
        Your logs here
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Add any other context about the problem here
    validations:
      required: false
